package server

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The document must describe the type the handler PARSES, not one that looks
// like it.
//
// docs/openapi.yaml is generated by reflecting over the value handed to
// routeIn, and TestTheDocumentMatchesTheRoutes fails when the document and
// that value disagree. Both were working. Neither was checking the thing that
// actually broke: for three routes the value handed to routeIn was a
// hand-written COPY of the handler's struct, so the generator described the
// copy, the test compared the document to the copy, and nobody compared the
// copy to the parser.
//
// The gear copy had already drifted. It declared args_schema and files as
// json.RawMessage — published as "any JSON value" — while handleCreateGear
// wanted a string and a []struct{Path,Content,Encoding}. Anyone who generated
// a client from the document and sent args_schema as the JSON object its name
// invites got 400 with "cannot unmarshal object into Go struct field
// .args_schema of type string". The whole point of publishing a description is
// that this cannot happen.
//
// This test closes it by reading the source: for every routeIn(..., handler,
// T{}) it finds the handler, finds what it decodes into, and requires that to
// be T. A copy can still be written — but it can no longer be handed to
// routeIn while the handler parses something else.
func TestADescribedBodyIsTheTypeTheHandlerParses(t *testing.T) {
	fset := token.NewFileSet()
	files := parsePackage(t, fset)

	described := describedRoutes(t, files) // handler name -> type named in routeIn
	if len(described) == 0 {
		t.Fatal("no routeIn calls found — this test has stopped reading the routing table")
	}

	decoded := decodeTargets(t, files) // function name -> type it decodes into
	calls := callGraph(files)          // function name -> the functions it calls
	aliases := aliasTargets(files)     // `type A = B` -> A resolves to B

	for handler, want := range described {
		got, ok := decoded[handler]
		if !ok {
			// Some handlers decode through a small helper (readInletTask) so
			// that two routes cannot accept different shapes for the same
			// thing. Follow one hop before concluding anything.
			for _, callee := range calls[handler] {
				if v, found := decoded[callee]; found {
					got, ok = v, true
					break
				}
			}
		}
		if !ok {
			// Registered as taking a body but never reading one is its own
			// bug, and not one this test invents a verdict for.
			t.Errorf("%s is registered with routeIn as taking %s, but it never decodes a body", handler, want)
			continue
		}
		// An alias IS the type, so CreateGearBody = createGearInput passes.
		// That is the fix this test is meant to accept; only a genuine second
		// declaration fails.
		if resolve(aliases, got) != resolve(aliases, want) {
			t.Errorf("%s decodes into %s, but the API document is generated from %s.\n"+
				"An integrator reads the schema reflected out of %s and sends a request %s refuses.\n"+
				"Make the described type an alias of the parsed one (see CreateGearBody) rather than a copy.",
				handler, got, want, want, handler)
		}
	}
}

func parsePackage(t *testing.T, fset *token.FileSet) []*ast.File {
	t.Helper()
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading the package directory: %v", err)
	}
	var out []*ast.File
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(".", name), nil, parser.ParseComments)
		if err != nil {
			t.Fatalf("parsing %s: %v", name, err)
		}
		out = append(out, f)
	}
	return out
}

// describedRoutes finds every `s.routeIn(mux, "...", s.handleX, T{})` and
// returns handleX -> "T".
func describedRoutes(t *testing.T, files []*ast.File) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, f := range files {
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "routeIn" || len(call.Args) != 4 {
				return true
			}
			handler := selectorName(call.Args[2])
			body := typeNameOfComposite(call.Args[3])
			if handler != "" && body != "" {
				out[handler] = body
			}
			return true
		})
	}
	return out
}

// decodeTargets finds, for each function, the type of the variable passed to
// decodeJSON. A handler that declares `var in T` and calls decodeJSON(w, r,
// &in) yields "T"; one that declares an anonymous struct yields a marker that
// can never equal a named type, which is exactly the failure being caught.
func decodeTargets(t *testing.T, files []*ast.File) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, f := range files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			// What does this function decode into, if anything?
			var target string
			ast.Inspect(fn, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}
				if id, ok := call.Fun.(*ast.Ident); !ok || id.Name != "decodeJSON" || len(call.Args) != 3 {
					return true
				}
				unary, ok := call.Args[2].(*ast.UnaryExpr)
				if !ok {
					return true
				}
				name := selectorName(unary.X)
				if name == "" {
					return true
				}
				target = declaredTypeOf(fn, name)
				return false
			})
			if target != "" {
				out[fn.Name.Name] = target
			}
		}
	}
	return out
}

// declaredTypeOf finds `var <name> T` inside fn and returns "T", or a marker
// when the declaration is an anonymous struct literal.
func declaredTypeOf(fn *ast.FuncDecl, name string) string {
	found := ""
	ast.Inspect(fn, func(n ast.Node) bool {
		decl, ok := n.(*ast.DeclStmt)
		if !ok {
			return true
		}
		gen, ok := decl.Decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			return true
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || vs.Type == nil {
				continue
			}
			for _, id := range vs.Names {
				if id.Name != name {
					continue
				}
				if ident, ok := vs.Type.(*ast.Ident); ok {
					found = ident.Name
				} else {
					found = "an anonymous struct declared inside the handler"
				}
			}
		}
		return true
	})
	return found
}

// callGraph maps each function to the names of the functions it calls, so a
// handler that decodes through a helper can still be checked.
func callGraph(files []*ast.File) map[string][]string {
	out := map[string][]string{}
	for _, f := range files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			ast.Inspect(fn, func(n ast.Node) bool {
				if call, ok := n.(*ast.CallExpr); ok {
					if name := selectorName(call.Fun); name != "" {
						out[fn.Name.Name] = append(out[fn.Name.Name], name)
					}
				}
				return true
			})
		}
	}
	return out
}

// aliasTargets collects `type A = B`, so an alias can be resolved to the type
// it names. An alias is not a copy — it is the same type under a second name,
// which is precisely the fix this test is meant to accept.
func aliasTargets(files []*ast.File) map[string]string {
	out := map[string]string{}
	for _, f := range files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || !ts.Assign.IsValid() {
					continue
				}
				if id, ok := ts.Type.(*ast.Ident); ok {
					out[ts.Name.Name] = id.Name
				}
			}
		}
	}
	return out
}

// resolve follows an alias chain to the underlying name.
func resolve(aliases map[string]string, name string) string {
	for i := 0; i < 10; i++ {
		next, ok := aliases[name]
		if !ok {
			return name
		}
		name = next
	}
	return name
}

// selectorName reduces `s.handleX` to "handleX" and a bare `in` to "in".
func selectorName(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.SelectorExpr:
		return v.Sel.Name
	case *ast.Ident:
		return v.Name
	}
	return ""
}

// typeNameOfComposite reduces `T{}` to "T".
func typeNameOfComposite(e ast.Expr) string {
	lit, ok := e.(*ast.CompositeLit)
	if !ok {
		return ""
	}
	if id, ok := lit.Type.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}
