package server

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// docs/openapi.yaml is generated from the running server's own route table.
//
// Not hand-written, and not generated by a build step somebody has to remember
// to run: this test regenerates it and fails when the committed file differs.
// So the only way to add a route without updating the description is to add a
// route and not run the tests, which CI does not allow.
//
//	go test ./internal/server -run TestOpenAPI -update
//
// rewrites it after a deliberate change.
var update = flag.Bool("update", false, "rewrite docs/openapi.yaml from the current routes")

func TestOpenAPIDescribesEveryRouteThisServerServes(t *testing.T) {
	d := newDoor(t)
	got := openAPI(d.srv.Routes())

	path := filepath.Join("..", "..", "docs", "openapi.yaml")
	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		t.Log("rewrote", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v\n\nRun: go test ./internal/server -run TestOpenAPI -update", path, err)
	}
	if string(want) != got {
		t.Fatalf("docs/openapi.yaml no longer matches the routes this server registers.\n"+
			"A route was added, removed or renamed without the description following it.\n\n"+
			"Run: go test ./internal/server -run TestOpenAPI -update\n\n%s",
			firstDifference(string(want), got))
	}
}

// The inventory is only worth anything if it is complete, so this checks the
// property directly rather than trusting that every registration went through
// the recorder.
func TestEveryRouteIsRecorded(t *testing.T) {
	d := newDoor(t)
	routes := d.srv.Routes()
	if len(routes) < 100 {
		t.Fatalf("only %d routes recorded, and this server has well over a hundred — "+
			"a registration is bypassing s.route", len(routes))
	}
	// Two that must always be there, one of each kind: an open one and a
	// delivery one. If the recorder ever stops seeing a class of route, this
	// says so rather than the count merely drifting.
	var health, delivery bool
	for _, r := range routes {
		if r.Path == "/health" && r.Auth == AuthNone {
			health = true
		}
		if strings.HasPrefix(r.Path, "/i/") && r.Auth == AuthInletKey {
			delivery = true
		}
	}
	if !health || !delivery {
		t.Fatalf("the inventory is missing a whole class of route: health=%v delivery=%v", health, delivery)
	}
}

// firstDifference points at the line that changed, because a diff of a
// thousand-line document is not a message.
func firstDifference(want, got string) string {
	w, g := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		lw, lg := "", ""
		if i < len(w) {
			lw = w[i]
		}
		if i < len(g) {
			lg = g[i]
		}
		if lw != lg {
			return fmt.Sprintf("first difference at line %d:\n  committed: %s\n  current:   %s", i+1, lw, lg)
		}
	}
	return "the files differ but no line does, which means one ends without a newline"
}
