{{- if or (and .Values.auth.adminToken (not .Values.auth.existingSecret)) (and .Values.config.egressKey (not .Values.config.egressExistingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogitorium.fullname" . }}-auth
  labels: {{- include "cogitorium.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.auth.adminToken (not .Values.auth.existingSecret) }}
  admin-token: {{ .Values.auth.adminToken | quote }}
  {{- end }}
  {{- if and .Values.config.egressKey (not .Values.config.egressExistingSecret) }}
  egress-key: {{ .Values.config.egressKey | quote }}
  {{- end }}
{{- end }}
